name: simsports one build main

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "./db/**"
      - "**.md"

jobs:
  frontend:
    name: Frontend Mobile Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - name: Check out branch
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npm run build:pro

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.0
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: /home/ubuntu/worker/simsports/frontend/pc/
          remote_host: ${{ secrets.DEPLOY_IP_PROD }}
          remote_user: ubuntu
          remote_key: ${{ secrets.DEPLOY_KEY_PROD }}
