// 分类数据
export const categories = [
	{ id: "all", name: "All" },
	{ id: "survival", name: "Survival" },
	{ id: "moba", name: "MOBA" },
	{ id: "fps", name: "FPS" },
	{ id: "rpg", name: "RPG" },
	{ id: "sag", name: "SAG" },
	{ id: "act", name: "ACT" },
	{ id: "acg", name: "AVG" },
	{ id: "casual", name: "Casual" },
	{ id: "simulation", name: "Simulation" },
];

// mock-Market 数据
export const mockMarketData = [
	{
		id: "1",
		name: "Last One",
		category: "Survival",
		volume: "$24m Vol.",
		predictions: [
			{ name: "First-night survival rate", value: "58%", isYes: true },
			{ name: "Shelter constructed", value: "35%", isYes: true },
			{ name: "Resource gathering success", value: "54%", isYes: true },
			{ name: "Mutant encounter event", value: "47%", isYes: false },
			{ name: "First-day community formed", value: "21%", isYes: true },
		],
	},
	{
		id: "2",
		name: "Outlive",
		category: "Survival",
		volume: "$18m Vol.",
		predictions: [
			{ name: "Third-day survival rate", value: "42%", isYes: true },
			// { name: "Water source located", value: "28%", isYes: true },
			{ name: "Food spoilage event", value: "39%", isYes: false },
			{ name: "Fire started successfully", value: "62%", isYes: true },
			{ name: "Bandit raid encounter", value: "33%", isYes: false },
		],
	},
	{
		id: "3",
		name: "Legends Arena",
		category: "MOBA",
		volume: "$55m Vol.",
		predictions: [
			{ name: "Red team victory", value: "47%", isYes: false },
			{ name: "Blue team victory", value: "42%", isYes: true },
			{ name: "Average game duration >25m", value: "38%", isYes: false },
			{ name: "First tower destroyed", value: "51%", isYes: true },
			{ name: "Baron Nashor taken", value: "29%", isYes: true },
		],
	},
	{
		id: "4",
		name: "Mythic Clash",
		category: "MOBA",
		volume: "$48m Vol.",
		predictions: [
			{ name: "First blood by mid-laner", value: "36%", isYes: true },
			{ name: "Dragon stolen", value: "22%", isYes: false },
			{ name: "Tower trade occurs", value: "44%", isYes: true },
			// { name: "Game ends under 30m", value: "27%", isYes: true },
			{ name: "Ace occurs", value: "15%", isYes: false },
		],
	},
	{
		id: "5",
		name: "Urban Warfare",
		category: "FPS",
		volume: "$60m Vol.",
		predictions: [
			{ name: "Team deathmatch win", value: "52%", isYes: true },
			{ name: "Bomb defused", value: "41%", isYes: true },
			// { name: "Headshot rate >20%", value: "33%", isYes: false },
			{ name: "Round win streak ≥3", value: "19%", isYes: true },
			{ name: "First-round ace", value: "12%", isYes: false },
		],
	},
	{
		id: "6",
		name: "Tactical Strike",
		category: "FPS",
		volume: "$52m Vol.",
		predictions: [
			{ name: "Objective secured", value: "37%", isYes: true },
			{ name: "Sniper kill", value: "28%", isYes: true },
			{ name: "Flanking maneuver success", value: "24%", isYes: true },
			{ name: "Team wipe", value: "16%", isYes: false },
			{ name: "Bomb plant success", value: "44%", isYes: true },
		],
	},
	{
		id: "7",
		name: "Eternal Saga",
		category: "RPG",
		volume: "$40m Vol.",
		predictions: [
			{ name: "Main quest completed", value: "68%", isYes: true },
			{ name: "Side quest completion", value: "52%", isYes: true },
			{ name: "Rare item found", value: "17%", isYes: false },
			{ name: "Max level reached", value: "29%", isYes: false },
			{ name: "NPC ally recruited", value: "33%", isYes: true },
		],
	},
	{
		id: "8",
		name: "Lost Horizons",
		category: "SAG",
		volume: "$22m Vol.",
		predictions: [
			{ name: "Puzzle solved", value: "45%", isYes: true },
			{ name: "Clue discovered", value: "38%", isYes: true },
			{ name: "Secret ending unlocked", value: "12%", isYes: false },
			{ name: "Time trial beaten", value: "27%", isYes: true },
			{ name: "Hidden area found", value: "31%", isYes: true },
		],
	},
	{
		id: "9",
		name: "Blaze of Glory",
		category: "ACT",
		volume: "$30m Vol.",
		predictions: [
			{ name: "Combo chain ≥50", value: "23%", isYes: true },
			{ name: "Boss damage >25%", value: "34%", isYes: false },
			{ name: "Stage cleared without hit", value: "14%", isYes: false },
			{ name: "Secret weapon used", value: "19%", isYes: true },
			{ name: "Time bonus achieved", value: "41%", isYes: true },
		],
	},
	{
		id: "10",
		name: "Mystic Tales",
		category: "AVG",
		volume: "$15m Vol.",
		predictions: [
			{ name: "True ending reached", value: "18%", isYes: true },
			{ name: "Romance route completed", value: "26%", isYes: true },
			{ name: "All CGs unlocked", value: "11%", isYes: false },
			{ name: "No-skip playthrough", value: "22%", isYes: true },
			{ name: "Alternate scenario seen", value: "14%", isYes: false },
		],
	},
	{
		id: "11",
		name: "Casual Craft",
		category: "Casual",
		volume: "$12m Vol.",
		predictions: [
			{ name: "Daily login streak ≥7", value: "65%", isYes: true },
			{ name: "Level-up within 10 minutes", value: "48%", isYes: true },
			{ name: "In-app purchase", value: "27%", isYes: false },
			{ name: "Social share action", value: "22%", isYes: true },
			{ name: "Ad watch for reward", value: "33%", isYes: true },
		],
	},
	{
		id: "12",
		name: "City Simulator",
		category: "Simulation",
		volume: "$38m Vol.",
		predictions: [
			{ name: "Population >10k", value: "57%", isYes: true },
			{ name: "City budget balanced", value: "43%", isYes: true },
			{ name: "Disaster event occurred", value: "19%", isYes: false },
			// { name: "Public transport implemented", value: "32%", isYes: true },
			// { name: "Pollution level ≤50", value: "28%", isYes: true },
		],
	},
];
